version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::417146377129:user/testPipelineRoles-DevStagePipelineUser-QKEXA95VR7OB"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::417146377129:role/testPipelineRoles-DevStagePipelineExecutionRole-FKA4IPL9JIBI"
cloudformation_execution_role = "arn:aws:iam::417146377129:role/testPipelineRoles-DevStagePipelineCloudFormationEx-CDTHZ0YHQWR2"
artifacts_bucket = "arn:aws:s3:::testpipelineroles-devstagepipelinesampackageartif-nebpgn6z9tz4"
image_repository = ""
region = "us-east-1"
